Erros de estorno para API de Pagamentos em Lote
imobanco/bb-wrapper pull request #34
Opened 2022-08-02 14:05 UTC by rodrigondec

# Resumo
> erro 'Dígito da conta de crédito não informado. Informe o DV da conta de crédito.'
>  https://discord.com/channels/692426888563523716/1002309822605185104/1002309828418490419
> https://forum.developers.bb.com.br/t/erro-digito-da-conta-de-credito-nao-informado/20686

>  erro 'Conta de crédito informada não é numérica. Informe apenas números.'
> https://discord.com/channels/692426888563523716/992442302997987328/992442308882612376
> https://forum.developers.bb.com.br/t/erro-conta-de-credito-informada-nao-e-numerica/20269

Na API de lotes de pagamento, quando ocorre um erro, é retornado um código de erro. Com esse código de erro, é possível utilizar uma tabela de tradução para o motivo correto do erro.

O problema é que só existe a (tabela de erros de **VALIDAÇÃO** na documentação da API)[https://apoio.developers.bb.com.br/referency/post/62055ff0842bcd00126d7582].

E não existe a tabela de erros de **ESTORNO**. Em comunicação com o BB, foi adquirida uma relação dos erros de estorno.

Esse PR adiciona justamente o novo dict de tradução de erros de estorno. E atualiza os erros de validação.

2022-08-02 14:08 UTC, PedroRegisPOAR approved these changes
Aprovado.

2022-08-02 16:04 UTC, PedroRegisPOAR reviewed
Acho que todas as mensagens de erro podem acabar com `.`

Achava que essas mensagens tinham que ser mantidas exatamente conforme recebidas

2022-08-02 16:04 UTC, PedroRegisPOAR commented on bb_wrapper/models/pagamentos.py
> +    1: "Conta destinatária do credito encerrada",
```suggestion
    1: "Conta destinatária do crédito encerrada",
```

2022-08-02 16:04 UTC, PedroRegisPOAR commented on bb_wrapper/models/pagamentos.py
> +    2: "Agencia ou conta destinatária do credito invalida",
```suggestion
    2: "Agência ou conta destinatária do credito inválida",
```

2022-08-02 16:04 UTC, PedroRegisPOAR commented on bb_wrapper/models/pagamentos.py
> +    4: "Msg invalida p/ o tipo de transação ou finalidade",
```suggestion
    4: "Msg inválida p/ o tipo de transação ou finalidade",
```

2022-08-02 16:04 UTC, PedroRegisPOAR commented on bb_wrapper/models/pagamentos.py
> +    22: "Devolução de ordem bancaria pelo agente financeiro",
```suggestion
    17: "Número de contrato inválido",
    18: "Valor em duplicidade",
    19: "Mov. finc. ligadas ao terrorismo e seu financiamento",
    22: "Devolução de ordem bancária pelo agente financeiro",
```

2022-08-02 16:04 UTC, PedroRegisPOAR commented on bb_wrapper/models/pagamentos.py
> +    15: "Identificação deposito Judicial Invalida",
```suggestion
    8: "Código identificador de transferência inválido",
    9: "Devolução por fraude",
    15: "Identificação deposito Judicial Inválida",
```

2022-08-02 16:48 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    24: "CPF igual a Zeros. Obrigatório informar o nº do CPF.",
```suggestion
    24: "CPF igual a zeros. Obrigatório informar o nº do CPF.",
```

2022-08-02 16:48 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    28: "Credito não sacado - decurso de prazo estipulado",
```suggestion
    28: "Crédito não sacado - decurso de prazo estipulado",
```

2022-08-02 16:48 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    98: "Código de tipo de conta do Cliente do Pix não foi informado",
Eu achava que o correto era 'Pix', é como vejo escreverem na internet. Até tinha atualizado na documentação.

2022-08-02 16:48 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    25: "Erro no Preenchimento do Deposito Direto",
```suggestion
    25: "Erro no Preenchimento do Depósito Direto",
```

2022-08-02 16:48 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    22: "Devolução de ordem bancaria pelo agente financeiro",
```suggestion
    22: "Devolução de ordem bancária pelo agente financeiro",
```

2022-08-02 16:48 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    17: "Numero de contrato invalido",
```suggestion
    17: "Número de contrato inválido",
```

2022-08-02 16:48 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    16: "Msg STRO020/PAG0116 fora do horário def do negocio",
```suggestion
    16: "Mensagem STRO020/PAG0116 fora do horário def do negócio",
```

2022-08-02 16:48 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    15: "Identificação deposito Judicial Invalida",
```suggestion
    15: "Identificação Depósito Judicial inválida",
```

2022-08-02 16:48 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    8: "Código identificador de transferência invalido",
```suggestion
    8: "Código identificador de transferência inválido",
```

2022-08-02 16:48 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    4: "Msg invalida p/ o tipo de transação ou finalidade",
```suggestion
    4: "Mensagem inválida para o tipo de transação ou finalidade",
```

2022-08-02 16:48 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    2: "Agencia ou conta destinatária do credito invalida",
```suggestion
    2: "Agência ou conta destinatária do crédito inválida",
```

2022-08-02 16:48 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    1: "Conta destinatária do credito encerrada",
```suggestion
    1: "Conta destinatária do crédito encerrada",
```

2022-08-02 16:48 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    6: "Transferência insuficiente p/ finalidade indicada",
```suggestion
    6: "Transferência insuficiente para finalidade indicada",
```

2022-08-02 16:48 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    84: "Ct destino inválida p/ o tp de trans ou finalidade",
O que `tp de trans` significa?
```suggestion
    84: "Conta destino inválida para o tp de trans ou finalidade",
```

2022-08-02 16:48 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    70: "Por solicitação de cliente da Inst Partcpt Receb",
O que "Inst Partcpt Receb" significa?

2022-08-02 16:48 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    61: "Transf supera limite para o tipo de conta destino",
```suggestion
    61: "Transferência supera limite para o tipo de conta destino",
```

2022-08-02 16:48 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    31: "CPF/CNPJ inapto junto a receita federal do Brasil",
```suggestion
    31: "CPF/CNPJ inapto junto a Receita Federal do Brasil",
```

2022-08-02 16:48 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    27: "Devolc de recolhimento a maior autorizada pela RFB",
Essa frase tá estranha.
```suggestion
    27: "Devolução de recolhimento a maior autorizada pela Receita Federal do Brasil",
```

2022-08-02 16:48 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    26: "Devolc. de pagmnt de tributos por solicitação da IF",
O que é IF?
```suggestion
    26: "Devolução de pagamento de tributos por solicitação da IF",
```

2022-08-02 16:48 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    19: "Mov. finc. ligadas ao terrorismo e seu financiamento",
```suggestion
    19: "Movimentações finceiras ligadas ao terrorismo e seu financiamento",
```

2022-08-02 16:48 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    332: "Beneficiário divergente. ",
```suggestion
    332: "Beneficiário divergente.",
```

2022-08-02 16:48 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    218: "Data Lançamento Inválido",
```suggestion
    218: "Data Lançamento Inválida",
```

2022-08-02 16:48 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    117: "Nº de identifiação do contribuinte DARF inválido. Informe um número válido.",
Acho que seria bom padronizar o uso de "Número" ao invés de "Nº"
```suggestion
    117: "Número de identifiação do contribuinte DARF inválido. Informe um número válido.",
```

2022-08-02 16:48 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    80: "Conta de crédito inválida. Informe o numero   sem o 45 do início.",
```suggestion
    80: "Conta de crédito inválida. Informe o numero sem o 45 do início.",
```

2022-08-02 16:55 UTC, Matheusouto requested changes

2022-08-02 16:55 UTC, Matheusouto commented on bb_wrapper/models/pagamentos.py
> +    15: "Digito da conta de crédito inválido.",
15: "Dígito da conta de crédito inválido.",

2022-08-02 17:05 UTC, rodrigondec commented on bb_wrapper/models/pagamentos.py
> +    98: "Código de tipo de conta do Cliente do Pix não foi informado",
No, o termo correto é tudo maiúsculo mesmo no PIX.

Tem o material do banco central sobre. Um manual de desenvolvimento/padronização

2022-08-02 17:11 UTC, rodrigondec commented on bb_wrapper/models/pagamentos.py
> +    80: "Conta de crédito inválida. Informe o numero   sem o 45 do início.",
outdated

2022-08-02 17:11 UTC, rodrigondec commented on bb_wrapper/models/pagamentos.py
> +    15: "Digito da conta de crédito inválido.",
@Matheusouto tem a funcionalidade de sugerir alteração. Pede para alguém da equipe te mostrar e explicar como usa

2022-08-02 17:13 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    4: "Msg inválida p/ o tipo de transação ou finalidade",
```suggestion
    4: "Mensagem inválida para o tipo de transação ou finalidade",
```

2022-08-02 17:13 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    2: "Agência ou conta destinatária do credito inválida",
```suggestion
    2: "Agência ou conta destinatária do crédito inválida",
```

2022-08-02 17:14 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    15: "Identificação deposito Judicial Inválida",
```suggestion
    15: "Identificação Depósito Judicial inválida",
```

2022-08-02 17:15 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    16: "Mensagem STRO020/PAG0116 fora do horário def do negócio",
"def" seria deferimento?
```suggestion
    16: "Mensagem STRO020/PAG0116 fora do horário def do negócio",
```

2022-08-02 17:15 UTC, rodrigondec commented on bb_wrapper/models/pagamentos.py
> +    70: "Por solicitação de cliente da Inst Partcpt Receb",
eu chutaria "instituição participante do recebimento"

Vulgo, "Por solicitação de cliente no banco de destino".

Mas não tenho certeza

2022-08-02 17:19 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    122: "Nº de identificação do contribuinte GPS inválido. Informe um número válido.",
```suggestion
    122: "Número de identificação do contribuinte GPS inválido. Informe um número válido.",
```

2022-08-02 17:21 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    84: "Conta destino inválida para o tp de trans ou finalidade",
O que `tp de trans` significa? Acho melhor deixar mais clara a mensagem.

2022-08-02 17:24 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    210: "Nº Sequencial do Registro no Lote Inválido",
```suggestion
    210: "Número Sequencial do Registro no Lote Inválido",
```

2022-08-02 17:25 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    214: "Nº do ISPB Banco, Instituição de Pagamento para crédito Inválido",
```suggestion
    214: "Número do ISPB Banco, Instituição de Pagamento para crédito Inválido",
```

2022-08-02 17:25 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    228: "Nº do Banco para crédito Inválido",
```suggestion
    228: "Número do Banco para crédito Inválido",
```

2022-08-02 17:25 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    224: "Nº do Local do Favorecido Não Informado",
```suggestion
    224: "Número do Local do Favorecido Não Informado",
```

2022-08-02 17:26 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    64: "Nº de Identificação do Contribuinte não numérico",
```suggestion
    64: "Número de Identificação do Contribuinte não numérico",
```

2022-08-02 17:26 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    63: "Nº de Identificação do Contribuinte não informado",
```suggestion
    63: "Número de Identificação do Contribuinte não informado",
```

2022-08-02 17:26 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    1: "Agência de crédito igual a zero. Informe o nº da Agência de Crédito.",
```suggestion
    1: "Agência de crédito igual a zero. Informe o número da Agência de Crédito.",
```

2022-08-02 17:26 UTC, brenov commented on bb_wrapper/models/pagamentos.py
>      22: "Número ISPB diferente de zeros. Não informe o nº ISPB.",
```suggestion
    22: "Número ISPB diferente de zeros. Não informe o número ISPB.",
```

2022-08-02 17:27 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    24: "CPF igual a zeros. Obrigatório informar o nº do CPF.",
```suggestion
    24: "CPF igual a zeros. Obrigatório informar o número do CPF.",
```

2022-08-02 17:27 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    43: "Dígito do CPF para o pagador inválido. Verifique o nº correto.",
```suggestion
    43: "Dígito do CPF para o pagador inválido. Verifique o número correto.",
```

2022-08-02 17:27 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    44: "Dígito do CPF para o beneficiário inválido. Verifique o nº correto.",
```suggestion
    44: "Dígito do CPF para o beneficiário inválido. Verifique o número correto.",
```

2022-08-02 17:27 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    45: "Dígito do CPF para o avalista inválido. Verifique o nº correto.",
```suggestion
    45: "Dígito do CPF para o avalista inválido. Verifique o número correto.",
```

2022-08-02 17:27 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    46: "Dígito do CNPJ para o pagador inválido. Verifique o nº correto.",
```suggestion
    46: "Dígito do CNPJ para o pagador inválido. Verifique o número correto.",
```

2022-08-02 17:27 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    47: "Dígito do CNPJ para o beneficiário inválido. Verifique o nº correto.",
```suggestion
    47: "Dígito do CNPJ para o beneficiário inválido. Verifique o número correto.",
```

2022-08-02 17:27 UTC, brenov commented on bb_wrapper/models/pagamentos.py
> +    48: "Dígito do CNPJ para o avalista inválido. Verifique o nº correto.",
```suggestion
    48: "Dígito do CNPJ para o avalista inválido. Verifique o número correto.",
```

2022-08-02 17:28 UTC, Matheusouto commented on bb_wrapper/models/pagamentos.py
> +    15: "Digito da conta de crédito inválido.",
```suggestion
    15: "Dígito da conta de crédito inválido.",
```

2022-08-02 17:31 UTC, rodrigondec commented on bb_wrapper/models/pagamentos.py
> +    84: "Conta destino inválida para o tp de trans ou finalidade",
tipo de transferência, provavelmente

2022-08-02 17:31 UTC, rodrigondec commented on bb_wrapper/models/pagamentos.py
> +    16: "Mensagem STRO020/PAG0116 fora do horário def do negócio",
definido

2022-08-03 03:30 UTC, rodrigondec commented on bb_wrapper/models/pagamentos.py
> +    84: "Conta destino inválida para o tp de trans ou finalidade",
Feito

2022-08-03 03:30 UTC, rodrigondec commented on bb_wrapper/models/pagamentos.py
> +    16: "Mensagem STRO020/PAG0116 fora do horário def do negócio",
Feito

2022-08-03 03:32 UTC, merged