Refactor/oauth
imobanco/bb-wrapper pull request #37
Opened 2022-08-05 13:14 UTC by brenov

# Resumo

Relacionado aos issues/prs:
- https://github.com/imobanco/bb-wrapper/issues/36

## Como estava antes

Cada interação com a API BB realizava duas requisições: uma de autenticação e a ação (get, post, etc.).

## Como ficará

Passaremos a salvar o token de autenticação no BaseBBWrapper para solicitar autenticação apenas quando o token expirar.

# Alterações de models
- [ ] Sim
- [x] Não

# Alterações de services
- [ ] Sim
- [x] Não

# Alterações de wrappers
- [x] Sim
- [ ] Não

Foi adicionado o atributo `login` para salvar o token de autorização e os métodos HTTP foram sobrescritos para garantir que as requisições estejam autenticadas.

# Outros ajustes

Ajusta ambiente de desenvolvimento do nix.

2022-08-05 13:42 UTC, rodrigondec requested changes
Vejo duas estratégias que podem ser utilizadas para resolver o problema.


- try/retry tratando um erro de 401/403
- autenticação idempotente com melhor inteligência para evitar retry

No momento você está fazendo um pouco das duas :thinking:

2022-08-05 13:42 UTC, rodrigondec commented on bb_wrapper/constants.py
> +class AuthorizationDeniedEnum(Enum):
acho isso overengenieering :thinking: 

Principalmente pq tira um pouco da legibilidade na verificação que é feita.

Agora está 
```python
if code in AuthorizationDeniedEnum.values():
    pass
```

Sem isso ficaria
```python
if code in [401, 403]:
    pass
```

2022-08-05 13:42 UTC, rodrigondec commented on bb_wrapper/wrapper/bb.py
> +
Não precisa dessa variável de controle!

Já existe o `__access_token`, basta utilizar ele!

```suggestion
```

2022-08-05 13:42 UTC, rodrigondec commented on bb_wrapper/wrapper/bb.py
> +        return self.__login
Não precisa dessas alterações no código!

Basta usar o `__access_token` para realizar o controle da autenticação!

Seria bom também mudar o método para privado
> de `authenticate` para `__authenticate`

2022-08-05 13:42 UTC, rodrigondec commented on bb_wrapper/wrapper/bb.py
> +            self.__login = self._process_response(self.__login)
Se você quiser deixar o `authenticate` **idempotente** dando refresh na autenticação se necessário, recomendo fazer a decodar o token.

O token é um JWT. O que significa que no próprio token tem o seu tempo de duração. 

Ou seja, não seria necessário tentar fazer uma requisição e tomar um 403 para **SABER** que é necessário se autenticar novamente!

2022-08-05 13:42 UTC, rodrigondec commented on bb_wrapper/wrapper/bb.py
> +        self.authenticate()
Fazendo os métodos de maneira mais inteligente, isso não vai ser necessário :thinking:

2022-08-05 13:42 UTC, rodrigondec commented on bb_wrapper/wrapper/bb.py
> +        return response
Esse tratamento de erros está meio estranho!

1. caso não seja um problema de autenticação, o erro precisa ser levantado adiante novamente!
2. pode ser utilizado recursão para fazer o retry da requisição original
3. está muito branda a verificação, qualquer 401 ou 403 tenta autenticar novamente

```suggestion
        except HTTPError as err:
            if err.response.status_code in AuthorizationDeniedEnum.values():
                self.reauthenticate()
                return = self._delete(url, headers)
            raise err

        return response
```

2022-08-05 13:42 UTC, rodrigondec commented on bb_wrapper/wrapper/bb.py
> +            self.authenticate()
Se em todos vai ser mantido o `authenticate`, uma estratégia melhor seria fazer o decode do JWT e **SABER** previamente (sem fazer a requisição e sem ser necessário try/except) se é necessário:
1. se autenticar do zero (primeiro request)
2. autenticar novamente (token expirado)

2022-08-05 13:42 UTC, rodrigondec commented on bb_wrapper/wrapper/bb.py
> +                response = err.response
Esse trecho de código está replicado em cada um dos 5 métodos (get, post, delete, put e patch).

É possível reaproveitar ele com um pouco de engenharia de software!

2022-08-05 13:45 UTC, brenov commented on bb_wrapper/constants.py
> +class AuthorizationDeniedEnum(Enum):
Posso utilizar também uma lista na classe, já que uso essa lista em outros métodos. O que acha?

2022-08-05 13:46 UTC, rodrigondec commented on bb_wrapper/constants.py
> +class AuthorizationDeniedEnum(Enum):
Acho que seria melhor sim

2022-08-05 14:16 UTC, brenov commented on bb_wrapper/wrapper/bb.py
> +            self.__login = self._process_response(self.__login)
Nesse caso eu precisaria utilizar uma biblioteca nova né? Não encontrei nenhuma referência a JWT no projeto.

2022-08-05 20:38 UTC, rodrigondec requested changes
Já está quase lá na implementação :clap: 

Próxima semana a gente foca nos testes disso!

2022-08-05 20:38 UTC, rodrigondec commented on bb_wrapper/wrapper/bb.py
> +    def __authenticate(self, force=False):
```suggestion
    def __authenticate(self, force_auth=False):
```

2022-08-05 20:38 UTC, rodrigondec commented on bb_wrapper/wrapper/bb.py
> +        if self.__access_token is None or force is True:
```suggestion
        if self.__access_token is None or force_auth is True:
```

2022-08-05 20:38 UTC, rodrigondec commented on bb_wrapper/wrapper/bb.py
> +            response = request_method(*args, **kwargs)
Já está mt melhor :clap: 

Agora só falta adivinhar se vai ser necessário se autenticar/reautenticar **ANTES** de fazer a requisiação original.

Para isso, precisará ser feito a verificação de tempo do token.

E ai, podemos iniciar com a estratégia de armazenar em uma variável a hora da autenticação original ou algo assim. Enquanto não conseguimos analisar de fato o JWE

2022-08-05 20:38 UTC, rodrigondec commented on bb_wrapper/wrapper/bb.py
> +
Tem que armazenar os dados da autenticação em um storage compartilhado entre as diversas instâncias!

Se não fizer isso, a cada nova instância do wrapper será necesário se reautenticar!

```suggestion
    data = threading.local()
```

2022-08-05 20:38 UTC, rodrigondec commented on bb_wrapper/wrapper/bb.py
> +            self.__token_type = response.data["token_type"]
```suggestion
            self.data.access_token = response.data["access_token"]
            self.data.token_type = response.data["token_type"]
```

2022-08-05 20:38 UTC, rodrigondec commented on bb_wrapper/wrapper/bb.py
> +        if self.__access_token is None or force is True:
```suggestion
        if self.data.access_token is None or force is True:
```

2022-08-08 13:11 UTC, brenov commented on bb_wrapper/wrapper/bb.py
> +            response = request_method(*args, **kwargs)
Feito.

2022-08-08 15:06 UTC, rodrigondec requested changes
Agora é só focar na refatoração pra deixar legal :muscle: 

E os testes

2022-08-08 15:06 UTC, rodrigondec commented on bb_wrapper/wrapper/bb.py
> +        return self.__do_request(super()._patch, url, data, headers, use_json)
Com todas as refatorações feitas e códigos mais enxutos, não precisa mais também fazer o strategy pattern!

Já que teoricamente, seria necessário chamar o `__authenticate` antes de qualquer requisição


```suggestion
    def _delete(self, url, headers=None) -> requests.Response:
        self.__authenticate()
        return super()._delete(url, headers)

    def _get(self, url, headers=None) -> requests.Response:
        self.__authenticate()
        return super()._get(url, headers)

    def _post(self, url, data, headers=None, use_json=True) -> requests.Response:
        self.__authenticate()
        return super()._post(url, data, headers, use_json)

    def _put(self, url, data, headers=None, use_json=True) -> requests.Response:
        self.__authenticate()
        return super()._put(url, data, headers, use_json)

    def _patch(self, url, data, headers=None, use_json=True) -> requests.Response:
        self.__authenticate()
        return super()._patch(url, data, headers, use_json)
```

2022-08-08 15:06 UTC, rodrigondec commented on bb_wrapper/wrapper/bb.py
> +        response = request_method(*args, **kwargs)
```suggestion
```

2022-08-08 15:06 UTC, rodrigondec commented on bb_wrapper/wrapper/bb.py
> +        if self.data.access_token is None or force_auth is True:
Seria algo nesse estilo
```suggestion
        elapsed_time = time.time() - self.data.token_time
        if elapsed_time >= self.TOKEN_TIME:
            force_auth = True
        if self.data.access_token is None or force_auth is True:
```

2022-08-08 18:00 UTC, brenov commented on bb_wrapper/wrapper/bb.py
> +    data = threading.local()
Fuciona sim

2022-08-08 18:02 UTC, brenov commented on bb_wrapper/wrapper/bb.py
> +    data = threading.local()
Testei aqui, funciona sim

2022-08-08 18:29 UTC, brenov commented on bb_wrapper/wrapper/bb.py
> +    TOKEN_TIME_ERROR = 5  # 5 seconds
Eu adicionei pensando em evitar mandar uma requisição usando um token expirado. Mas lembrei agora que a API pode ficar instável e é melhor pensar em como tratar uma requisição com token expirado.

2022-08-08 18:46 UTC, brenov commented on bb_wrapper/wrapper/bb.py
> +    data = threading.local()
Por alguma razão muito estranha, tá dando problema ao acessar o `__data` no teste de reautenticação.

`AttributeError: 'BaseBBWrapper' object has no attribute '_BaseBBWrapperTestCase__data'`

2022-08-09 14:11 UTC, rodrigondec commented on bb_wrapper/wrapper/bb.py
> +    TOKEN_TIME_ERROR = 5  # 5 seconds
Acredito que não tem problema com relação à isso não precisa se preocupar.

A instabilidade sempre vai existir e não tem como tratar ela.

Se for uma instabilidade de demora de requisição não há impacto.

2022-08-09 15:10 UTC, rodrigondec requested changes
O token não está sendo compartilhado entre as instâncias

2022-08-09 15:10 UTC, rodrigondec commented on requirements.txt
> +freezegun==1.1.0
O freezegun deveria ser uma dependência DEV

2022-08-09 17:50 UTC, PedroRegisPOAR reviewed
Alguns comentários numa primeira olhada.

2022-08-09 17:50 UTC, PedroRegisPOAR commented on flake.nix
> +
```suggestion
          # Se não existir cria o .env com valores padrão
          if ! test -f .env; then
            make config.env
          fi
```

2022-08-09 17:50 UTC, PedroRegisPOAR commented on README.rst
> +    make poetry.install
Da forma como o devShell está é possível remover esses comandos.

Ou seja, basta fazer `nix develop` e a mágica acontece.
```suggestion
```

2022-08-09 17:50 UTC, PedroRegisPOAR commented on README.rst
> +    direnv allow
```suggestion
    nix develop
```

2022-08-09 17:50 UTC, PedroRegisPOAR commented on bb_wrapper/wrapper/bb.py
> +        if not hasattr(self.__data, "token_type") or not self.__data.token_type:
Curioso, não basta apenas uma dessas "expressões"?

Ou apenas `not hasattr(self.__data, "token_type")`

Ou apenas `not self.__data.token_type`?

2022-08-09 17:50 UTC, PedroRegisPOAR commented on bb_wrapper/wrapper/bb.py
> +        if not hasattr(self.__data, "access_token") or not self.__data.access_token:
Mesmo caso do outro comentário :thinking:

2022-08-09 17:50 UTC, PedroRegisPOAR commented on bb_wrapper/wrapper/bb.py
> +        if not hasattr(self.__data, "token_time") or not self.__data.token_time:
Mesmo caso do outro comentário :thinking:

2022-08-09 18:39 UTC, rodrigondec requested changes
:rocket:

2022-08-09 18:39 UTC, rodrigondec commented on bb_wrapper/wrapper/bb.py
> +    UNAUTHORIZED = [401, 403]
```suggestion
```

2022-08-09 18:39 UTC, rodrigondec commented on bb_wrapper/wrapper/bb.py
> +        self.__data.access_token = value
```suggestion
```

2022-08-09 18:39 UTC, rodrigondec commented on bb_wrapper/wrapper/bb.py
> +        self.__data.token_type = value
```suggestion
```

2022-08-09 18:39 UTC, rodrigondec commented on bb_wrapper/wrapper/bb.py
> +        self.__data.token_time = value
```suggestion
```

2022-08-09 18:39 UTC, rodrigondec commented on bb_wrapper/wrapper/bb.py
> +            self.__token_time = datetime.now()
```suggestion
            self.__data.access_token = response.data["access_token"]
            self.__data.token_type = response.data["token_type"]
            self.__data.token_time = datetime.now()
```

2022-08-09 21:03 UTC, rodrigondec requested changes

2022-08-09 21:03 UTC, rodrigondec commented on tests/wrapper/test_bb_base.py
> +        self.assertEqual(bb_wrapper2._access_token, "token_1")
O teste está cosntruído de uma forma que não identificou o erro do reset do data no __new__!

```suggestion
        bb_wrapper1 = BaseBBWrapper()
        result1 = bb_wrapper1._BaseBBWrapper__authenticate()
        self.assertEqual(result1, True)
        self.assertEqual(bb_wrapper1._access_token, "token_1")

        bb_wrapper2 = BaseBBWrapper()
        result2 = bb_wrapper2._BaseBBWrapper__authenticate()
        self.assertEqual(result2, False)
        self.assertEqual(bb_wrapper2._access_token, "token_1")
```

2022-08-09 21:03 UTC, rodrigondec commented on tests/wrapper/test_bb_base.py
> +        )
Além disso, pode-se colocar o assert do mock para garantir que só foi feita uma única vez a requisição

```suggestion
        )
        
        self.mocked_auth_requests.post.assert_called_once()
```

2022-08-10 11:45 UTC, brenov commented on bb_wrapper/wrapper/bb.py
> +        cls.reset_data()
Eu suspeitei que isso poderia causar falhas em alguns testes, testei aqui e foi o que aconteceu.

Usando o Debug eu vi que `cls._data` tem valor de objeto de propriedade (ex: `<property object at 0x7f4580702d60>`). Imagino que seja porque nesse momento é a referência da classe e não da instância. Assim, nunca a thread local é inicializada.

Como alternativa, eu pensei em colocar um `if not hasattr(cls, "__data"):` dentro de `reset_data`, ou seja, o atributo só é criado e inicializado se ele não existir. Testei assim e passou nos testes.

No caso, a função completa seria:
```
@classmethod
def reset_data(cls):
    if not hasattr(cls, "__data"):
        setattr(cls, f"_{cls.__name__}__data", threading.local())
```

2022-08-10 11:58 UTC, brenov commented on tests/wrapper/test_bb_base.py
> +        self.assertEqual(bb_wrapper2._access_token, "token_1")
A minha sugestão do comentário anterior não resolve o problema que tu descreveu aqui.

2022-08-10 12:35 UTC, brenov commented on bb_wrapper/wrapper/bb.py
> +        cls.reset_data()
Essa solução que eu propus não resolve o teste corrigido do acesso de múltiplas instâncias.

2022-08-10 12:47 UTC, brenov commented on bb_wrapper/wrapper/bb.py
> +        cls.reset_data()
Usei o `getattr(cls, f"_{cls.__name__}__data", None):` ao invés de chamar a propriedade `_data` no `reset_data`:
```
def reset_data(cls):
    if not getattr(cls, f"_{cls.__name__}__data", None):
        setattr(cls, f"_{cls.__name__}__data", threading.local())
```
Rodou corretamente nos testes individualmente, mas falhou em alguns erros ao rodar todos os testes. Exemplo:
```
FAIL: test_authentication_for_multiple_instances (tests.wrapper.test_bb_base.BaseBBWrapperTestCase)
Teste para verificar se o token de autenticação é utilizado
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/breno/Desktop/Projects/Imobanco/bb-wrapper/tests/wrapper/test_bb_base.py", line 67, in test_authentication_for_multiple_instances
    self.assertEqual(result1, True)
AssertionError: False != True

FAIL: test_cadastrar_pagamento_tributo_1 (tests.wrapper.test_pagamentos.PagamentoLoteBBWrapperTestCase)
Teste para verificar a URL da requisição e dados
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/breno/Desktop/Projects/Imobanco/bb-wrapper/tests/wrapper/test_pagamentos.py", line 285, in test_cadastrar_pagamento_tributo_1
    self.mocked_post.assert_called_with(
  File "/nix/store/nki9ywqzbvz68vr75kn2r7g1q84f5agy-python3-3.9.6/lib/python3.9/unittest/mock.py", line 907, in assert_called_with
    raise AssertionError(_error_message()) from cause
AssertionError: expected call not found.
```

2022-08-10 12:49 UTC, rodrigondec commented on bb_wrapper/wrapper/bb.py
> +        cls.reset_data()
Essa verificação tem que ser no __new__ mesmo.

O reset_data tem que redeclarar novamente mesmo, o objetivo dele é esse!

2022-08-10 12:54 UTC, brenov commented on bb_wrapper/wrapper/bb.py
> +        cls.reset_data()
Pode crer! Lembrei que ele é chamado no mock pra resetar lá. Já ajustei e isso ajudou a passar 2 testes. Agora tem 11 falhando, todos de `PagamentoLoteBBWrapperTestCase`, e todos `AssertionError: expected call not found.`.

Vou seguir investigando.

2022-08-10 13:55 UTC, rodrigondec commented on bb_wrapper/wrapper/bb.py
> +        cls.reset_data()
Vou dar uma olhada com vc jaja então

2022-08-10 15:52 UTC, rodrigondec approved these changes
:rocket:

2022-08-10 16:55 UTC, PedroRegisPOAR approved these changes
Aprovado.

Tem algumas sugestões bobas.

2022-08-10 16:55 UTC, PedroRegisPOAR commented on flake.nix
> +          fi
```suggestion
            # Se não existir cria o .env com valores padrão
            if ! test -f .env; then
              make config.env
            fi
```

2022-08-10 16:55 UTC, PedroRegisPOAR commented on tests/utils.py
> +        CobrancasBBWrapper().reset_data()
Qual o equivalente a esse código no "cliente" :thinking:

2022-08-10 16:55 UTC, PedroRegisPOAR commented on README.rst
> +> O NIX é utilizado para gerenciar os pacotes necessários, por exemplo como a versão correta do python.
```suggestion
> O Nix é utilizado para gerenciar os pacotes necessários, por exemplo como a versão correta do python.
```

2022-08-10 16:57 UTC, rodrigondec commented on tests/utils.py
> +        CobrancasBBWrapper().reset_data()
não entendi o questionamento

2022-08-10 17:06 UTC, PedroRegisPOAR approved these changes
:rocket:

2022-08-10 17:10 UTC, PedroRegisPOAR commented on tests/utils.py
> +        CobrancasBBWrapper().reset_data()
Resolvido.

2022-08-10 17:21 UTC, rodrigondec approved these changes

2022-08-10 17:37 UTC, arianesc approved these changes
Aprovado

2022-08-10 18:15 UTC, merged