Corrige erro de conexão "Connection reset by peer"
imobanco/bb-wrapper pull request #51
Opened 2022-11-25 18:59 UTC by brenov

# Resumo

Relacionado aos issues/prs:

- 

Algumas requisições a APIs de terceiros resultaram em erros de conexão com a seguinte mensagem: "Connection reset by peer".

Este PR corrige esse erro adicionando um método `_base_request` com sleep de 0.01 segundos.

# Alterações de models
- [ ] Sim
- [x] Não

# Alterações de services
- [ ] Sim
- [x] Não

# Alterações de wrappers
- [x] Sim
- [ ] Não

Adiciona método `_base_request` com sleep de 0.01 segundos.

2022-11-25 20:14 UTC, PedroRegisPOAR commented
Deu erro no coverage :eyes:

2022-11-28 21:44 UTC, rodrigondec requested changes

2022-11-28 21:44 UTC, rodrigondec commented on bb_wrapper/wrapper/request.py
> +
Precisa mesmo da complexidade de usar o wraps do functools?

E passar explicitamente o self? Ele já seria o primeiro arg sem definir ele como um arg da função `inner` 


```suggestion
def retry_request(counter=5):
    retry_request.counter = counter

    def wrapper(func, *args, **kwargs):

        def inner(*args, **kwargs):
            try:
                return func(*args, **kwargs)
            except (ConnectionError, ConnectionResetError, ProtocolError):
                retry_request.counter -= 1
                if retry_request.counter > 0:
                    return inner(*args, **kwargs)
                raise

        return inner

    return wrapper

```

2022-11-28 21:44 UTC, rodrigondec commented on bb_wrapper/wrapper/request.py
> +        sleep(0.01)
colocar o sleep no retry? :thinking:

2022-11-29 11:01 UTC, brenov commented on bb_wrapper/wrapper/request.py
> +
Eu tinha colocado pra seguir o tutorial, mas vou testar sem.

2022-11-29 11:08 UTC, brenov commented on bb_wrapper/wrapper/request.py
> +        sleep(0.01)
Feito

2022-11-29 12:17 UTC, brenov commented on bb_wrapper/wrapper/request.py
> +                if retry_request.counter > 0:
Existe um problema com a atribuição do contador direto na função.

Quando se decresce o contador em um método chamado, essa mudança é compartilhada por todos os métodos decorados por essa função.

2022-11-29 12:25 UTC, brenov commented on bb_wrapper/wrapper/request.py
> +                if retry_request.counter > 0:
Corrigi

2022-11-30 13:44 UTC, rodrigondec requested changes

2022-11-30 13:44 UTC, rodrigondec commented on tests/wrapper/test_request.py
> +        """
instala a lib do py-bdd-context e usa ela :grin:

2022-11-30 13:44 UTC, rodrigondec commented on tests/wrapper/test_request.py
> +        self.headers_patcher.stop()
Faltou só um assert de quantas vezes foi chamado

```suggestion
        self.assertEqual(self.mocked_headers.call_count, 3)

        self.headers_patcher.stop()
```

2022-11-30 13:44 UTC, rodrigondec commented on tests/wrapper/test_request.py
> +        self.headers_patcher.stop()
Faltou só um assert de quantas vezes foi chamado

```suggestion
        wrapper._get(url)
        
        self.assertEqual(self.mocked_headers.call_count, 3)

        self.headers_patcher.stop()
```

2022-11-30 13:44 UTC, rodrigondec commented on bb_wrapper/wrapper/request.py
> +                sleep(0.01)
pode aumentar esse sleep.

Poderia até colocar um random de 0.01 a 0.9 nesse valor

```suggestion
                sleep_time = random(1, 90)/100
                sleep(sleep_time)
```

2022-11-30 16:07 UTC, rodrigondec approved these changes

2022-11-30 16:25 UTC, rodrigondec approved these changes

2022-11-30 16:25 UTC, merged

2022-11-30 16:29 UTC, PedroRegisPOAR commented on examples/connection.py
> +            print("vou matar", str(p))
:eyes:

2022-11-30 16:33 UTC, PedroRegisPOAR reviewed
:eye:

2022-11-30 16:33 UTC, rodrigondec commented on examples/connection.py
> +            print("vou matar", str(p))
script só de debug haha