Método para retornar informações de um boleto.
imobanco/bb-wrapper pull request #58
Opened 2023-08-30 18:53 UTC by arianesc

A sysout precisa de um endpoint que retorne informações de um boleto com base no código de barra ou linha digitável.
Esse pr implementa o método que retorna as informações.
https://app.clickup.com/t/86a0ewfj5

2023-08-30 19:04 UTC, brenomfviana commented on bb_wrapper/services/barcode.py
> +        """
```suggestion
        due_date: vencimento (apenas para comercial)
        """
```

2023-08-30 19:04 UTC, brenomfviana commented on bb_wrapper/services/barcode.py
> +                "type": "Comercial",
Não tem enum pra esse valor?

2023-08-30 19:04 UTC, brenomfviana commented on bb_wrapper/services/barcode.py
> +                "type": "Tributo",
Não tem enum pra esse valor?

2023-08-30 19:04 UTC, rodrigondec requested changes

2023-08-30 19:04 UTC, rodrigondec commented on bb_wrapper/services/barcode.py
> +        raise ValidationError("tipo de boleto não identificado")
Eu refatoraria isso e colocaria essas 'retiradas' de informação em cada service dessas entidades e utilizaria um strategy para utilizar o service correto

2023-08-30 19:04 UTC, rodrigondec commented on bb_wrapper/services/barcode.py
> +        raise ValidationError("tipo de boleto não identificado")
```suggestion
        strategy_mapping = {
            BarcodeCobranca: BarcodeCobrancaService().get_info_from_barcode
            BarcodeTributo: BarcodeTributoService().get_info_from_barcode
        }
        action = strategy_mapping[instance.__class__]
        
        return action(instance)
```

2023-08-30 19:55 UTC, arianesc commented on bb_wrapper/services/barcode.py
> +                "type": "Comercial",
eu procurei, mas acho que não tem Enum com esses tipos.

2023-08-30 19:55 UTC, arianesc commented on bb_wrapper/services/barcode.py
> +                "type": "Tributo",
eu procurei, mas acho que não tem Enum com esses tipos.

2023-08-30 20:20 UTC, rodrigondec requested changes

2023-08-30 20:20 UTC, rodrigondec commented on bb_wrapper/services/barcode_cobranca.py
> +        }
```suggestion
    def get_infos_from_instance(self, instance):
        return {
            "instance": instance,
            "valid": True,
            "barcode_number": instance.barcode,
            "code_line": instance.code_line,
            "type": "Comercial",
            "bank": instance.barcode[:3],
            "amount": int(instance.barcode[9:19]),
            "due_date": self.calculate_due_date(instance.barcode[5:9]),
        }
```

2023-08-30 20:20 UTC, rodrigondec commented on bb_wrapper/services/barcode_tributo.py
> +        }
```suggestion
    def get_infos_from_instance(self, instance):
        return {
            "instance": instance,
            "valid": True,
            "barcode_number": instance.barcode,
            "code_line": instance.code_line,
            "type": "Tributo",
            "amount": int(instance.barcode[4:15]),
        }
```

2023-08-30 20:20 UTC, rodrigondec commented on bb_wrapper/services/barcode_tributo.py
> +            "amount": int(instance.barcode[4:15]),
Tem que estudar o `valor real ou referência` que afeta esse campo no tributo. Não sei se esse campo sempre terá o valor em centavos ou se teria um valor diferente...

2023-08-31 19:46 UTC, rodrigondec reviewed
Só ver essa parte do fator de vencimento e valor do tributo!

2023-09-04 18:01 UTC, arianesc commented on bb_wrapper/services/barcode_cobranca.py
> +        Os slices presentes nesse método estão documentad os na docstring do service!
```suggestion
        Os slices presentes nesse método estão documentados na docstring do service!
```

2023-09-04 18:03 UTC, arianesc commented on tests/services/test_barcode_cobranca.py
> +            - É dia 1902/2025
```suggestion
            - É dia 19/02/2025
```

2023-09-05 00:28 UTC, rodrigondec requested changes

2023-09-05 00:28 UTC, rodrigondec commented on bb_wrapper/services/barcode_cobranca.py
> +            "amount": int(instance.barcode[9:19]),
```suggestion
            "amount": int(instance.barcode[9:19])/100,
```

2023-09-05 00:28 UTC, rodrigondec commented on bb_wrapper/services/barcode_tributo.py
> +            "amount": int(instance.barcode[4:15]),
```suggestion
            "amount": int(instance.barcode[4:15])/100,
```

2023-09-05 00:28 UTC, rodrigondec commented on tests/services/test_barcode_cobranca.py
> +        self.assertEqual(str(result), "2025-03-03 00:00:00")
O resultado deveria ser um date, e não um datetime!

```suggestion
        self.assertEqual(str(result), "2025-03-03")
```

2023-09-05 00:28 UTC, rodrigondec commented on bb_wrapper/services/barcode_cobranca.py
> +        return base_date + fv
manipular para tranformar em date!

2023-09-05 00:28 UTC, rodrigondec commented on bb_wrapper/services/barcode_cobranca.py
> +        return base_date + fv
como foi chegado nesse cálculo?

2023-09-05 13:22 UTC, arianesc commented on bb_wrapper/services/barcode_cobranca.py
> +        return base_date + fv
Eu e Breno tentamos fazer de várias formas, mas no final a unica que passou em todos os testes foi essa que é:
1. Calcular com a data de 1997.
2. Se a data de vencimento ficar a mais de 10 anos atras, usar a data nova de 2025.
Mas isso vai depender do quanto dura um boleto também, colocamos 10 anos por alto. Por isso perguntamos se existe a possibilidade de ser consultado um boleto vencido  a mais de 10 anos.

2023-09-06 14:27 UTC, rodrigondec commented on bb_wrapper/services/barcode_cobranca.py
> +        return base_date + fv
Entendi, está bom esse método

2023-09-06 14:27 UTC, rodrigondec submitted a review, later dismissed

2023-09-06 14:38 UTC, PedroRegisPOAR reviewed
Um comentário, no mais LGTM

2023-09-06 14:38 UTC, PedroRegisPOAR commented on tests/services/test_barcode.py
> +        self.assertEqual(str(ctx.exception), "Tipo não identificado!")
Seria interessante que a mensagem de erro fosse um pouco mais específica?
```suggestion
        self.assertEqual(str(ctx.exception), "Tipo não é um código de barra válido ou linha digitável válida! ")
```

Dependendo do contexto de onde essa mensagem aparecer (em outros projetos por exemplo) pode ser complicado entender/lembrar ao que essa mensagem se refere :thinking:

2023-09-06 14:39 UTC, rodrigondec commented on tests/services/test_barcode.py
> +        self.assertEqual(str(ctx.exception), "Tipo não identificado!")
Acho pertinente. Eu diria até que pode colocar O seguinte

```suggestion
        self.assertEqual(str(ctx.exception), "Código de barras ou linha digitável inválida!")
```

2023-09-06 14:58 UTC, brenomfviana approved these changes
Só fazer o ajuste que Pedro e Rodrigo comentaram e tá show 🚀

2023-09-06 16:13 UTC, PedroRegisPOAR reviewed
Algumas vezes o Codecov já acertou em nos alertar sobre algo. Não sei o que se passa nesse caso.

2023-09-06 16:13 UTC, PedroRegisPOAR commented on tests/services/test_barcode.py
> +            - Deve ser retornado um ValueError com "Tipo não identificado!"
```suggestion
            - Deve ser retornado um ValueError com ""Código de barras ou linha digitável inválida!""
```

2023-09-06 16:13 UTC, PedroRegisPOAR commented on tests/services/test_barcode.py
> +        )
Pq será que o Codecov não identificou esse teste :thinking:

2023-09-06 17:16 UTC, rodrigondec requested changes

2023-09-06 17:16 UTC, rodrigondec commented on bb_wrapper/services/barcode.py
> +            raise ValueError("Código de barras ou linha digitável inválida!")
Se colocar um data vazio, vai passar e estourar as validações das duas instâncias? Caindo apenas no raise final? :thinking: 

```suggestion
            data = {}
```

2023-09-06 17:16 UTC, rodrigondec commented on bb_wrapper/services/barcode.py
> +        raise ValueError("Código de barras ou linha digitável inválida!")
Seria bom ter teste que cubra os dois raises, ou transformar os dois raises em um só :thinking:

2023-09-06 17:20 UTC, arianesc commented on bb_wrapper/services/barcode.py
> +            raise ValueError("Código de barras ou linha digitável inválida!")
Sim, dessa forma ele caiu no raise final.

2023-09-08 18:34 UTC, rodrigondec approved these changes

2023-09-08 18:35 UTC, merged