Adiciona suporte a transferências para contas pagamento
imobanco/bb-wrapper pull request #66
Opened 2023-11-30 19:35 UTC by brenomfviana

2023-11-30 19:40 UTC, rodrigondec commented on bb_wrapper/wrapper/pagamento_lote.py
> +            }
```suggestion
        elif None not in [agencia_destino, conta_destino, dv_conta_destino]:
            pagamento_data = {
                **pagamento_data,
                "agenciaCredito": agencia_destino,
                "contaCorrenteCredito": conta_destino,
                "digitoVerificadorContaCorrente": dv_conta_destino,
            }
        else:
            raise ValueError("Conta de Pagamento OU dados de conta corrente precisam ser informados")!
```

2023-11-30 19:49 UTC, PedroRegisPOAR reviewed
LGTM

2023-11-30 20:48 UTC, rodrigondec approved these changes

2023-12-01 14:09 UTC, PedroRegisPOAR approved these changes
:rocket:

2023-12-01 14:17 UTC, rodrigondec requested changes
:rocket:

2023-12-01 14:17 UTC, rodrigondec submitted a review, later dismissed
:rocket: 

Vou só fazer testes manuais agora!

2023-12-01 17:33 UTC, PedroRegisPOAR approved these changes
LGTM

2023-12-04 10:47 UTC, arianesc approved these changes

2023-12-04 10:47 UTC, arianesc commented on tests/wrapper/test_pagamentos.py
> +    def test_cadastrar_transferencia_3_vazio(self):
Os testes do bb-wrapper ficam sem o BDD mesmo?

2024-03-03 20:15 UTC, rodrigondec approved these changes
apenas um detalhe

2024-03-08 14:19 UTC, rodrigondec submitted a review, later dismissed

2024-03-08 16:31 UTC, brenomfviana commented on Makefile
> +	-mkdir certs
Tá certo ter esse traço na frente do comando?

2024-03-08 16:32 UTC, brenomfviana commented on bb_wrapper/wrapper/pagamento_lote.py
> +                "agenciaCredito": agencia_destino,
Aparentemente não precisa informar a agência para contas pagamento

2024-03-08 16:34 UTC, brenomfviana commented on bb_wrapper/wrapper/request.py
>          response.reason = response.data
Coloco if aqui também, @rodrigondec?

2024-03-08 17:19 UTC, rodrigondec commented on Makefile
> +	-mkdir certs
Sim. Isso faz com que seja ignorado um erro caso ocorra.

2024-03-08 17:20 UTC, rodrigondec commented on bb_wrapper/wrapper/request.py
>          response.reason = response.data
no `response.reason`? Eu diria que sim

2024-03-08 17:55 UTC, brenomfviana commented on bb_wrapper/wrapper/request.py
>          response.reason = response.data
Isso, feito

2024-07-23 14:51 UTC, brenomfviana commented on bb_wrapper/wrapper/pagamento_lote.py
> +            }
Já era pra ser possível realizar a transferência

2024-07-31 13:38 UTC, rodrigondec reviewed
Revisão atualizada. Aguardando testes de integração no ambiente de produção

2024-08-02 18:44 UTC, rodrigondec approved these changes

2024-08-02 18:44 UTC, merged