Atualiza versão da API de cobrança PIX v2
imobanco/bb-wrapper pull request #71
Opened 2024-07-16 11:49 UTC by peidrao

- [Atualizar versão da API PIX do BB [Clickup]](https://app.clickup.com/t/86a43kdxf)

2024-07-16 11:51 UTC, brenomfviana approved these changes

2024-07-16 12:22 UTC, Carvs10 approved these changes

2024-07-16 12:28 UTC, Carvs10 submitted a review, later dismissed

2024-07-18 18:17 UTC, brenomfviana approved these changes

2024-08-12 14:33 UTC, brenomfviana commented on tests/wrapper/test_pagamentos.py
> +            f"https://api-ip.sandbox.bb.com.br/pagamentos-lote/v1/"
Não é v2 aqui?

2024-08-12 14:36 UTC, brenomfviana approved these changes

2024-08-12 14:41 UTC, rodrigondec commented on tests/wrapper/test_pagamentos.py
> +            f"https://api-ip.sandbox.bb.com.br/pagamentos-lote/v1/"
Está errado essa manipulação que eu fiz.

2024-08-12 16:17 UTC, Carvs10 approved these changes

2024-08-12 19:30 UTC, rodrigondec commented on bb_wrapper/wrapper/pagamento_lote.py
> +    BASE_SUBDOMAIN = "api-ip"
Tem que desfazer essa alteração. Ficou errado a construção da URL por causa dessa alteração.

2024-08-12 19:33 UTC, rodrigondec commented on bb_wrapper/wrapper/pix_cob.py
> +    BASE_SANDBOX_ADDITION = "hm"
Acho que esse implementação não está legal. Acho que é melhor deixar explícito a URL de prod e a url de sandbox e fazer a escolhe disso com base na variável de sandbox.

2024-08-12 19:34 UTC, rodrigondec commented on tests/wrapper/test_pagamentos.py
> +            f"https://api-ip.sandbox.bb.com.br/pagamentos-lote/v1/"
Ficou errado. Deveria ser essa daqui

```Suggestion
            f"https://api.sandbox.bb.com.br/pagamentos-lote/v1/"
```

2024-08-12 21:36 UTC, rodrigondec requested changes

2024-08-12 21:36 UTC, rodrigondec commented on bb_wrapper/wrapper/bb.py
> +
pode refatorar esses atributos privados para protegidos.

2024-08-12 21:36 UTC, rodrigondec commented on bb_wrapper/wrapper/bb.py
> +            self.base_url = self.BASE_URL
isso vai quebrar os outros wrappers se eles não sobreescreverem esses atributos.

2024-08-12 21:36 UTC, rodrigondec commented on bb_wrapper/wrapper/pix_cob.py
> +        self.base_url = self.SANDBOX_BASE_URL if self._is_sandbox else self.BASE_URL
e se foi feito no BaseBBWrapper, não é necessário aqui!

2024-08-13 16:32 UTC, brenomfviana commented on bb_wrapper/wrapper/bb.py
> +    # BASE_SANDBOX_ADDITION = ".sandbox"
Remover?

2024-08-13 16:32 UTC, brenomfviana commented on bb_wrapper/wrapper/pagamento_lote.py
> +    # BASE_DOMAIN = ".bb.com.br/pagamentos-lote/v1"
Remover?

2024-08-14 13:35 UTC, rodrigondec requested changes

2024-08-14 13:35 UTC, rodrigondec commented on bb_wrapper/wrapper/bb.py
> +    @property
Acredito que tenha que corrigir o `__oauth_url` também

![image](https://github.com/user-attachments/assets/10d4b78e-ff95-4755-9934-6565b4351e4b)

![image](https://github.com/user-attachments/assets/418c14b9-3095-4776-a511-1cde9b4b932b)

2024-08-14 18:12 UTC, rodrigondec requested changes

2024-08-14 18:12 UTC, rodrigondec commented on bb_wrapper/wrapper/bb.py
>      BASE_DOMAIN = ".bb.com.br"
remover esses outros campos tbm!

```Suggestion

```

2024-08-14 19:55 UTC, rodrigondec commented on bb_wrapper/wrapper/bb.py
>      BASE_DOMAIN = ".bb.com.br"
Tem que deixar com if/else se for de sandbox ou não!

Mas pode deixar fixa sim.

- `https://oauth.sandbox.bb.com.br/oauth/token`
- `https://oauth.bb.com.br/oauth/token`

2024-08-14 20:12 UTC, rodrigondec approved these changes

2024-08-14 20:13 UTC, merged